replicaCount: 1

image:
  repository: your-custom-magento-image
  tag: latest
  pullPolicy: IfNotPresent

mysql:
  database: magento
  user: mysql-user
  storage:
    enabled: true
    size: 20Gi
    storageClassName: standard

elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
  replicaCount: 1
  storage:
    enabled: true
    size: 30Gi
    storageClassName: standard

