apiVersion: v1
kind: ConfigMap
metadata:
  name: magento-config
  namespace: magento
data:
  nginx.conf: |
    {{ .Files.Get "~/magento-deployment/nginx.conf" }}
  php-fpm.conf: |
    {{ .Files.Get "~/magento-deployment/php-fpm.conf" }}