apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv
  namespace: magento
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/elasticsearch

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  namespace: magento
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
