apiVersion: v1
kind: PersistentVolume
metadata:
  name: magento-pv
  namespace: magento
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/magento

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: magento-pvc
  namespace: magento
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
