apiVersion: apps/v1
kind: Deployment
metadata:
  name: magento
  namespace: magento
  labels:
    app: magento
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magento
  template:
    metadata:
      labels:
        app: magento
    spec:
      containers:
        - name: magento
          image: madnan08/magento-image:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MAGENTO_HOST
              value: "http://20.51.207.214:32000"
            - name: DB_HOST
              value: mysql
            - name: DB_NAME
              value: magentodb
            - name: DB_USER
              value: magentouser
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql-magento-password
            - name: MAGENTO_USERNAME
              value: admin
            - name: MAGENTO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: magento-secrets
                  key: admin-password
            - name: ELASTICSEARCH_HOST
              value: elasticsearch
            - name: PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: magento-auth-keys
                  key: public-key
            - name: PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: magento-auth-keys
                  key: private-key
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: magento-data
              mountPath: /var/www/magento2
            - name: magento-keys
              mountPath: "/root/.composer/"
              readOnly: true
      volumes:
        - name: magento-data
          persistentVolumeClaim:
            claimName: magento-pvc
        - name: magento-keys
          secret:
            secretName: magento-auth-keys
            items:
              - key: public-key
                path: auth.json
              - key: private-key
                path: auth.json
---
apiVersion: v1
kind: Service
metadata:
  name: magento
  namespace: magento
  labels:
    app: magento
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32000
  selector:
    app: magento