---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: magento
  namespace: magento
  labels:
    app: magento
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magento
  template:
    metadata:
      labels:
        app: magento
    spec:
      containers:
        - name: magento
          image: madnan08/magento-image:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              value: magentodb
            - name: MYSQL_USER
              value: "madnan08"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-magento-password
          volumeMounts:
            - name: magento-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: php-config
              mountPath: /usr/local/etc/php/php.ini
              subPath: php.ini
            - name: supervisord-config
              mountPath: /etc/supervisord.conf
              subPath: supervisord.conf
      volumes:
        - name: magento-config
          configMap:
            name: magento-config
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: php-config
          configMap:
            name: magento-config
            items:
              - key: php.ini
                path: php.ini
        - name: supervisord-config
          configMap:
            name: magento-config
            items:
              - key: supervisord.conf
                path: supervisord.conf
---
apiVersion: v1
kind: Service
metadata:
  name: magento
  namespace: magento
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: magento