apiVersion: apps/v1
kind: Deployment
metadata:
  name: magento
  namespace: magento
  labels:
    app: magento
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magento
  template:
    metadata:
      labels:
        app: magento
    spec:
      containers:
        - name: magento
          image: madnan08/magento-image:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MAGENTO_DATABASE_HOST
              value: mysql
            - name: MAGENTO_DATABASE_PORT_NUMBER
              value: "3306"
            - name: MAGENTO_DATABASE_NAME
              value: magentodb
            - name: MAGENTO_DATABASE_USER
              value: magentouser
            - name: MAGENTO_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql-magento-password
            - name: MAGENTO_HOST
              value: "http://20.51.207.214:9000"
            - name: MAGENTO_USERNAME
              value: admin
            - name: MAGENTO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: magento-secrets
                  key: admin-password
          ports:
            - name: http
              containerPort: 9000
          volumeMounts:
            - name: magento-data
              mountPath: /var/www/magento2
      initContainers:
        - name: magento-setup
          image: madnan08/magento-image:latest
          imagePullPolicy: IfNotPresent
          command: ["/usr/local/bin/start.sh"]
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_NAME
              value: magentodb
            - name: DB_USER
              value: magentouser
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql-magento-password
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql-root-password
            - name: ELASTICSEARCH_HOST
              value: elasticsearch
          volumeMounts:
            - name: magento-data
              mountPath: /var/www/magento2
      volumes:
        - name: magento-data
          persistentVolumeClaim:
            claimName: magento-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: magento
  namespace: magento
  labels:
    app: magento
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 9000
      nodePort: 32000
  selector:
    app: magento