apiVersion: apps/v1
kind: Deployment
metadata:
  name: magento
  namespace: magento
  labels:
    app: magento
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magento
  template:
    metadata:
      labels:
        app: magento
    spec:
      containers:
        - name: magento
          image: madnan08/magento-deployment:3.5
          imagePullPolicy: IfNotPresent
          env:
            - name: MAGENTO_HOST
              value: "http://4.242.20.137:32000"
            - name: DB_HOST
              value: mysql
            - name: DB_NAME
              value: magentodb
            - name: DB_USER
              value: magentouser
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql-magento-password
            - name: MAGENTO_USERNAME
              value: admin
            - name: ADMIN_EMAIL
              value: adnan.sarfraz.2302105@gmail.com
            - name: MAGENTO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: magento-secrets
                  key: admin-password
            - name: ELASTICSEARCH_HOST
              value: elasticsearch
            - name: PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: magento-auth-keys
                  key: public-key
            - name: PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: magento-auth-keys
                  key: private-key
          ports:
            - name: http
              containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: magento
  namespace: magento
  labels:
    app: magento
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32000
  selector:
    app: magento
