apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: magento
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3N3b3Jk    
  mysql-magento-password: dGVhbWNpdHlwYXNzd29yZA==
---
apiVersion: v1
kind: Secret
metadata:
  name: magento-secrets
type: Opaque
data:
  admin-password: Um9vdHBhc3N3b3JkMTIz
---
apiVersion: v1
kind: Secret
metadata:
  name: magento-auth-keys
type: Opaque
data:
  public-key: "0c7abd45dec65b37db41137cbd3a435f",
  private-key: "1b7be114955c942c4d6c5422678ae660"
