apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: magento
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3N3b3Jk    
  mysql-magento-password: dGVhbWNpdHlwYXNzd29yZA==
---
apiVersion: v1
kind: Secret
metadata:
  name: magento-secrets
type: Opaque
data:
  admin-password: Um9vdHBhc3N3b3JkMTIz
---
apiVersion: v1
kind: Secret
metadata:
  name: magento-auth-keys
type: Opaque
data:
  public-key: MGM3YWJkNDVkZWM2NWIzN2RiNDExMzdjYmQzYTQzNWY=
  private-key: MWI3YmUxMTQ5NTVjOTQyYzRkNmM1NDIyNjc4YWU2NjA=