apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: magento
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3N3b3Jk    
  mysql-magento-password: dGVhbWNpdHlwYXNzd29yZA==
---
apiVersion: v1
kind: Secret
metadata:
  name: magento-secrets
type: Opaque
data:
  admin-password: Um9vdHBhc3N3b3JkMTIz
---
apiVersion: v1
kind: Secret
metadata:
  name: magento-auth-keys
type: Opaque
data:
  auth.json: ewogICAgImh0dHAtYmFzaWMiOiB7CiAgICAgICAgInJlcG8ubWFnZW50by5jb20iOiB7CiAgICAgICAgICAgICJ1c2VybmFtZSI6ICIwYzdhYmQ0NWRlYzY1YjM3ZGI0MTEzN2NiZDNhNDM1ZiIsCiAgICAgICAgICAgICJwYXNzd29yZCI6ICIxYjdiZTExNDk1NWM5NDJjNGQ2YzU0MjI2NzhhZTY2MCIKICAgICAgICB9CiAgICB9Cn0K
