apiVersion: v1
kind: ConfigMap
metadata:
  name: magento-config
data:
  nginx.conf: |
    {{ .Files.Get "~/magento-deployment/nginx.conf" }}
  php.ini: |
    {{ .Files.Get "~/magento-deployment/php.ini" }}
  supervisord.conf: |
    {{ .Files.Get "~/magento-deployment/supervisord.conf" }}
