apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-pv-claim
  labels:
    component: elasticsearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.elasticsearch.storage.size | default "30Gi" }}
  storageClassName: {{ .Values.elasticsearch.storage.storageClassName | default "standard" }}
