apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: magento-data
  labels:
    component: magento
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.magento.storage.size | default "20Gi" }}
  storageClassName: {{ .Values.magento.storage.storageClassName | default "standard" }}
