apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    component: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.storage.size | default "10Gi" }}
  storageClassName: {{ .Values.mysql.storage.storageClassName | default "standard" }}
